from typing import Any, Optional, Protocol

from src.application.dto import UserDTO


class UserDAO(Protocol):
    async def create(self, user: UserDTO) -> UserDTO: ...
    async def get(self, telegram_id: int) -> Optional[UserDTO]: ...
    async def get_by_ids(self, telegram_ids: list[int]) -> list[UserDTO]: ...
    async def get_by_partial_name(self, query: str) -> list[UserDTO]: ...
    async def update(self, telegram_id: int, **data: Any) -> Optional[UserDTO]: ...
    async def delete(self, telegram_id: int) -> bool: ...
    async def count(self) -> int: ...
